//================================================================================//
//                            DO NOT EDIT THIS FILE                               //
//   It is automatically generated from an obn file, changes will not be saved.   //
//================================================================================//

const React = require('react');

function Main({ loadAsync }) {
    let [state, setState] = React.useState(null);
    let [val, setVal] = React.useState("Hello, ");
    
    let refresh = React.useCallback(() => {
        loadAsync("input").then(setState);
    }, []);

    let sendVal = () => {
        loadAsync("insert", { value: val }).then(refresh);
    }

    React.useEffect(() => {
        refresh();
    }, [refresh])
    
    return (
        <div>
            {state || "Loading..."}
            <button onClick={refresh}>Refresh</button>
            <input type="text" value={val} onChange={e => setVal(e.target.value)} />
            <button onClick={sendVal}>SEND</button>
        </div>
    );
}

module.exports = { main: Main };
