//================================================================================//
//                            DO NOT EDIT THIS FILE                               //
//   It is automatically generated from an obn file, changes will not be saved.   //
//================================================================================//

module.exports = {
	nodes: {
		"7c": require('./7c/_index'),
	},
	output: "7c",
	graph: require('./_graph.json'),
};
