//================================================================================//
//                            DO NOT EDIT THIS FILE                               //
//   It is automatically generated from an obn file, changes will not be saved.   //
//================================================================================//



function main(o) {
    let connectionFactory = o.load("connection");
    let schema = o.load("schema");
    
    console.log(schema);
    return schema;
}

module.exports = { main };
