//================================================================================//
//                            DO NOT EDIT THIS FILE                               //
//   It is automatically generated from an obn file, changes will not be saved.   //
//================================================================================//

const _ = require('lodash');

function main(o) {
	return _.replace(o.load("a") + "&" + o.load("b"), "&", " ");
}

module.exports = { main };