//================================================================================//
//                            DO NOT EDIT THIS FILE                               //
//   It is automatically generated from an obn file, changes will not be saved.   //
//================================================================================//

module.exports = {
	nodes: {
		"Concat": require('./Concat'),
		"Part2": "\"World\"",
		"SqliteTable": require('./SqliteTable/_index'),
		"Sqlite": require('./Sqlite/_index'),
		"Key": "\"testingKey\"",
		"SetVal": require('./SetVal'),
	},
	output: "7c",
	graph: require('./_graph.json'),
};
