//================================================================================//
//                            DO NOT EDIT THIS FILE                               //
//   It is automatically generated from an obn file, changes will not be saved.   //
//================================================================================//

const _ = require('lodash');

async function main(o) {
	let t = o.load("table");
	let first = await t.get(o.load("key"), "...");

	return _.replace(first.value + "&" + o.load("b"), "&", " ");
}

module.exports = { main };