//================================================================================//
//                            DO NOT EDIT THIS FILE                               //
//   It is automatically generated from an obn file, changes will not be saved.   //
//================================================================================//

function main(o) {
    let id = o.load("key");
    let t = o.load("table");
    let value = o.value;

    t.insert({id, value});
}

module.exports = { main };
