//================================================================================//
//                            DO NOT EDIT THIS FILE                               //
//   It is automatically generated from an obn file, changes will not be saved.   //
//================================================================================//

module.exports = {
	nodes: {
		"SqliteConnection": require('./SqliteConnection'),
	},
	output: "SqliteConnection",
	graph: require('./_graph.json'),
};
