//================================================================================//
//                            DO NOT EDIT THIS FILE                               //
//   It is automatically generated from an obn file, changes will not be saved.   //
//================================================================================//

const sqlite = require('sqlite3').verbose();

function main(o) {
    return new sqlite.Database(o.load("location", err => {
        if (err) throw err;
    }));
}

module.exports = { main };

